# Generated by Django 2.2.13 on 2020-08-27 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attendence',
            table=None,
        ),
    ]
