# Generated by Django 2.2.13 on 2020-08-27 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20200827_1107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendence',
        ),
    ]
