# Generated by Django 2.2.13 on 2020-08-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200826_2054'),
        ('attendence', '0003_delete_attendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
    ]
