# Generated by Django 2.2.13 on 2020-08-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='is_onTime',
            field=models.CharField(default='', max_length=12, verbose_name='到课情况'),
        ),
    ]
